# Generated by Django 3.1.3 on 2023-01-11 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230111_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='ph',
        ),
    ]
