# Generated by Django 4.1.1 on 2023-01-11 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_contact_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='ph',
            new_name='phone',
        ),
    ]
